version: "3.9"

networks:
  default:
    name: ${APP_NAME}-network

services:
  mysql:
    container_name: ${APP_NAME}-mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile.local
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/docker-entrypoint-initdb.d:rw

  app:
    container_name: ${APP_NAME}-app
    hostname: app
    restart: always
    build:
      dockerfile: ./app/Dockerfile.local
      context: .
      args:
        environ: development
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
    links:
      - mysql
